# Generated by Django 5.1.6 on 2025-02-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_consultant_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
