# Generated by Django 5.1.6 on 2025-02-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_feedback_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='service_items',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
