# Generated by Django 5.1.6 on 2025-02-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_consultant_service_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='detailed_introduction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
